### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/iampavangandhi.github.io#3]
Need Improvement in Responsiveness and User Interface of the Web Pages. This repo is open for quality contributions only not for 2-3lines tiny things.

**Comment by sairajchouhan** [comment]
Hey @iampavangandhi  I wanna work on this

**Comment by sairajchouhan** [comment]
https://sairaj.netlify.app/ checkout my portfolio I can add value to your site

**Comment by iampavangandhi** [comment]
@sairaj2119 Nice portfolio :+1: Yes you can take the issue and start working

**Comment by sairajchouhan** [comment]
Yes, I am working on it

**Comment by iampavangandhi** [comment]
**Note:** This issue is still open if anyone wants to contribute :smile:

**Comment by Asritha1200** [comment]
Can u assign this to me?

**Comment by iampavangandhi** [comment]
@Asritha1200 Yes, you can take this. The main issues are in the contact form and in the mobile responsiveness (priority).

**Comment by arbazkhan56** [comment]
Can u assign me?

**Comment by iampavangandhi** [comment]
@arbazkhan56 Okay you also try

**Comment by FantasticMrHurst** [comment]
Hi @iampavangandhi, I submitted a pr for the contact form responsiveness. Please let me know if everything is to your liking. Happy Hacktoberfest!
