### ISSUE TITLE
Section about gets overflowing in mobile

### ISSUE THREAD

**Issue by vitormateusalmeida** [iampavangandhi/iampavangandhi.github.io#6]
![image](https://user-images.githubusercontent.com/9675166/94811994-7ff66d00-03cc-11eb-9f6f-c3abe472723b.png)

Colors in the contact section do not match the layout

![image](https://user-images.githubusercontent.com/9675166/94812147-b92edd00-03cc-11eb-84dd-287a0a5b6b55.png)

**Comment by iampavangandhi** [comment]
@vitormateusalmeida Thanks for pointing the issue although the second one is not an issue its a design choice
